pipeline {
    agent any
     stages 
    {   
        stage('Boost')
        {
            steps
            {
                sh 'wget https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz'
                sh 'tar xvf boost_1_65_1.tar.gz'
                sh 'cd boost_1_65_1'
                sh './bootstrap.sh --without-libraries=log'
                sh './bjam -d+2 -j 4 cxxflags="-std=c++11" variant=release link=shared threading=multi'
            }
        } 
        stage('Build') 
        {
            steps 
            {
                sh 'scons install DEBUG=1'
            }
        }
    }
}